# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kyha/Downloads/lab9_pl_camera_verilog/lab9_pl_camera_verilog.srcs/sources_1/ip/ram_camera/ram_camera.xci
# IP: The module: 'ram_camera' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kyha/Downloads/lab9_pl_camera_verilog/lab9_pl_camera_verilog.gen/sources_1/ip/ram_camera/ram_camera_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_camera'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/kyha/Downloads/lab9_pl_camera_verilog/lab9_pl_camera_verilog.srcs/sources_1/ip/ram_camera/ram_camera.xci
# IP: The module: 'ram_camera' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kyha/Downloads/lab9_pl_camera_verilog/lab9_pl_camera_verilog.gen/sources_1/ip/ram_camera/ram_camera_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_camera'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
