set_property PACKAGE_PIN "D7" [get_ports "sysclk_i"]
set_property CLOCK_DEDICATED_ROUTE FALSE  [get_nets "sysclk_i"]
set_property PACKAGE_PIN "F8" [get_ports "rst_ni"]
set_property PACKAGE_PIN "G1" [get_ports "TFTLCD_TCLK_o"]
set_property PACKAGE_PIN "E4" [get_ports "TFTLCD_hsync_o"]
set_property PACKAGE_PIN "F1" [get_ports "TFTLCD_vsync_o"]
set_property PACKAGE_PIN "E3" [get_ports "TFTLCD_de_out_o"]
set_property PACKAGE_PIN "R3" [get_ports "TFTLCD_data_o[15]"]
set_property PACKAGE_PIN "U2" [get_ports "TFTLCD_data_o[14]"]
set_property PACKAGE_PIN "U1" [get_ports "TFTLCD_data_o[13]"]
set_property PACKAGE_PIN "T3" [get_ports "TFTLCD_data_o[12]"]
set_property PACKAGE_PIN "T2" [get_ports "TFTLCD_data_o[11]"]
set_property PACKAGE_PIN "M1" [get_ports "TFTLCD_data_o[10]"]
set_property PACKAGE_PIN "M5" [get_ports "TFTLCD_data_o[9]"]
set_property PACKAGE_PIN "M4" [get_ports "TFTLCD_data_o[8]"]
set_property PACKAGE_PIN "L2" [get_ports "TFTLCD_data_o[7]"]
set_property PACKAGE_PIN "L1" [get_ports "TFTLCD_data_o[6]"]
set_property PACKAGE_PIN "P3" [get_ports "TFTLCD_data_o[5]"]
set_property PACKAGE_PIN "N2" [get_ports "TFTLCD_data_o[4]"]
set_property PACKAGE_PIN "P1" [get_ports "TFTLCD_data_o[3]"]
set_property PACKAGE_PIN "N5" [get_ports "TFTLCD_data_o[2]"]
set_property PACKAGE_PIN "N4" [get_ports "TFTLCD_data_o[1]"]
set_property PACKAGE_PIN "M2" [get_ports "TFTLCD_data_o[0]"]
set_property PACKAGE_PIN "E1" [get_ports "TFTLCD_Tpower_o"]
set_property PACKAGE_PIN "A7" [get_ports "camera_PWDN_o"]
set_property PACKAGE_PIN "A6" [get_ports "camera_RESETn_o"]
set_property PACKAGE_PIN "E6" [get_ports "camera_SCL_b"]
set_property PACKAGE_PIN "G6" [get_ports "camera_SDA_b"]
set_property PACKAGE_PIN "F7" [get_ports "camera_HSYNC_i"]
set_property PACKAGE_PIN "G7" [get_ports "camera_VSYNC_i"]
set_property IOSTANDARD "LVCMOS33" [get_ports "camera_PCLK_i"]
set_property PACKAGE_PIN "G5" [get_ports "camera_PCLK_i"]
set_property CLOCK_DEDICATED_ROUTE FALSE  [get_nets "camera_PCLK_i"]
set_property PACKAGE_PIN "F6" [get_ports "camera_MCLK_o"]
set_property PACKAGE_PIN "E5" [get_ports "camera_data_i[0]"]
set_property PACKAGE_PIN "D6" [get_ports "camera_data_i[1]"]
set_property PACKAGE_PIN "D5" [get_ports "camera_data_i[2]"]
set_property PACKAGE_PIN "C7" [get_ports "camera_data_i[3]"]
set_property PACKAGE_PIN "B6" [get_ports "camera_data_i[4]"]
set_property PACKAGE_PIN "C5" [get_ports "camera_data_i[5]"]
set_property PACKAGE_PIN "E8" [get_ports "camera_data_i[6]"]
set_property PACKAGE_PIN "D8" [get_ports "camera_data_i[7]"]

#set_property PACKAGE_PIN "" [get_ports "filter_size_switch_i[3]"]
#set_property PACKAGE_PIN "" [get_ports "filter_size_switch_i[2]"]
#set_property PACKAGE_PIN "" [get_ports "filter_size_switch_i[1]"]
#set_property PACKAGE_PIN "" [get_ports "filter_size_switch_i[0]"]


set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 26]]

set_property IOSTANDARD LVCMOS12 [get_ports -of_objects [get_iobanks 65]]
